# Generated by Django 6.0.5 on 2026-05-15 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('Research', 'Academic Research'), ('Scholarship', 'Scholarship'), ('Opportunity', 'Business Opportunity')], default='Research', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('external_url', models.URLField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='climate_ideas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='documents/')),
                ('file_size', models.CharField(blank=True, help_text='e.g. 8.57 MB', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(blank=True, max_length=100)),
                ('author_photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('tiktok_url', models.URLField(blank=True)),
                ('tiktok_id', models.CharField(blank=True, max_length=100)),
                ('custom_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
