# Generated by Django 6.0.5 on 2026-05-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mrs Alimat Oladipupo Jinadu S.', max_length=100)),
                ('role', models.CharField(default='Founder', max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='founder/')),
            ],
        ),
        migrations.CreateModel(
            name='NegligenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How to Conquer the Negligence of Climate Change in Africa', max_length=255)),
                ('author', models.CharField(default='Mrs Alimat Oladipupo Jinadu S.', max_length=100)),
                ('description', models.TextField()),
                ('quote', models.CharField(default='Negligence is expensive — but action is priceless.', max_length=255)),
                ('file', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Alimat Sustainability Climate Goal', max_length=255)),
                ('hero_subtitle', models.TextField(default='Empowering communities to discover the truth about climate change through reading, writing, and action.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('intro_title', models.CharField(default='Introduction to Climate Change in Africa', max_length=255)),
                ('intro_description', models.TextField(default='Climate change is not just a global issue — it’s a story that affects every home, business, and community in Africa.')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('vision', models.TextField(default='A climate-resilient Africa built on education and sustainable action.')),
                ('mission', models.TextField(default='To raise awareness and drive climate action through learning, creativity, and youth empowerment.')),
                ('values', models.TextField(default='Education | Inclusion | Sustainability | Innovation | Community')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
