# Generated by Django 6.0.3 on 2026-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
