# Generated by Django 6.0.3 on 2026-05-16 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_videoarticle_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimateIdea',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='NegligenceBook',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='founder',
            name='image',
        ),
        migrations.AddField(
            model_name='founder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='founder/'),
        ),
        migrations.AddField(
            model_name='videoarticle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(default='Ibraheem', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Empowering the next generation with the knowledge and tools to drive climate resilience across Africa.'),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='author_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='category',
            field=models.CharField(default='TikTok Series', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoarticle',
            name='description',
            field=models.TextField(),
        ),
    ]
