# Generated by Django 6.0.3 on 2026-05-16 11:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_climateidea_delete_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(default='TikTok Series', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tiktok_url', models.URLField(blank=True)),
                ('tiktok_id', models.CharField(blank=True, max_length=100)),
                ('custom_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('is_featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.author')),
            ],
            options={
                'verbose_name': 'Climate Article',
                'verbose_name_plural': 'Climate Articles',
            },
        ),
        migrations.CreateModel(
            name='ResearchResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('external_url', models.URLField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Research Resource',
                'verbose_name_plural': 'Research Resources',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='VideoArticle',
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(default='Mrs Alimat Oladipupo Jinadu S.', max_length=100),
        ),
    ]
