# Generated by Django 6.0.3 on 2026-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_author_climatearticles_researchresources_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climatearticles',
            old_name='tiktok_id',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='climatearticles',
            name='tiktok_url',
        ),
        migrations.AddField(
            model_name='climatearticles',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('youtube', 'YouTube')], default='tiktok', max_length=10),
        ),
        migrations.AddField(
            model_name='climatearticles',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste your TikTok or YouTube link here'),
        ),
        migrations.AlterField(
            model_name='climatearticles',
            name='category',
            field=models.CharField(default='Video Insights', max_length=100),
        ),
    ]
