# Generated by Django 6.0.3 on 2026-05-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_tiktok_id_climatearticles_video_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatearticles',
            name='content',
            field=models.TextField(blank=True, help_text='Write your full article content here.'),
        ),
        migrations.AddField(
            model_name='climatearticles',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
