# Generated by Django 6.0.3 on 2026-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_climatearticles_content_climatearticles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography of the author.'),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
