# Generated by Django 6.0.3 on 2026-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatearticles',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=10),
        ),
    ]
