# Generated by Django 6.0.3 on 2026-05-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_climatearticles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatearticles',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.author'),
        ),
    ]
