# Generated by Django 6.0.3 on 2026-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_climatearticles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload an MP4 video to use as the hero background.', null=True, upload_to='site/'),
        ),
    ]
