# Generated by Django 6.0.3 on 2026-05-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, default='<h2>Privacy Policy</h2><p>Your privacy policy content goes here...</p>'),
        ),
    ]
